cleaningcompany/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('companyapp.urls')),
    url(r'^newsletter/', include('newsletter.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),


]

markdownx/urls.py
"""
**MarkdownX** default URLs, to be added to URLs in the main project.

See URLs in :doc:`../../example` to learn more.
"""

from django.conf.urls import url

from .views import (
    ImageUploadView,
    MarkdownifyView,
)


urlpatterns = [
    url(r'^upload/$', ImageUploadView.as_view(), name='markdownx_upload'),
    url(r'^markdownify/$', MarkdownifyView.as_view(), name='markdownx_markdownify'),
]

newsletter/urls.py
from surlex.dj import surl

from .views import (
    NewsletterListView, NewsletterDetailView,
    SubmissionArchiveIndexView, SubmissionArchiveDetailView,
    SubscribeRequestView, UnsubscribeRequestView, UpdateRequestView,
    ActionTemplateView, UpdateSubscriptionView,
)

urlpatterns = [
    # Newsletter list and detail view
    surl('^$', NewsletterListView.as_view(), name='newsletter_list'),
    surl(
        '^<newsletter_slug:s>/$',
        NewsletterDetailView.as_view(), name='newsletter_detail'
    ),

    # Action request views
    surl(
        '^<newsletter_slug:s>/subscribe/$',
        SubscribeRequestView.as_view(),
        name='newsletter_subscribe_request'
    ),
    surl(
        '^<newsletter_slug:s>/subscribe/confirm/$',
        SubscribeRequestView.as_view(confirm=True),
        name='newsletter_subscribe_confirm'
    ),
    surl(
        '^<newsletter_slug:s>/update/$',
        UpdateRequestView.as_view(),
        name='newsletter_update_request'
    ),
    surl(
        '^<newsletter_slug:s>/unsubscribe/$',
        UnsubscribeRequestView.as_view(),
        name='newsletter_unsubscribe_request'
    ),
    surl(
        '^<newsletter_slug:s>/unsubscribe/confirm/$',
        UnsubscribeRequestView.as_view(confirm=True),
        name='newsletter_unsubscribe_confirm'
    ),

    # Activation email sent view
    surl(
        '^<newsletter_slug:s>/<action=subscribe|update|unsubscribe>/'
        'email-sent/$',
        ActionTemplateView.as_view(
            template_name='newsletter/subscription_%(action)s_email_sent.html'
        ),
        name='newsletter_activation_email_sent'),

    # Action confirmation views
    surl(
        '^<newsletter_slug:s>/subscription/<email=[-_a-zA-Z0-9@\.\+~]+>/'
        '<action=subscribe|update|unsubscribe>/activate/<activation_code:s>/$',
        UpdateSubscriptionView.as_view(), name='newsletter_update_activate'
    ),
    surl(
        '^<newsletter_slug:s>/subscription/<email=[-_a-zA-Z0-9@\.\+~]+>/'
        '<action=subscribe|update|unsubscribe>/activate/$',
        UpdateSubscriptionView.as_view(), name='newsletter_update'
    ),

    # Action activation completed view
    surl(
        '^<newsletter_slug:s>/<action=subscribe|update|unsubscribe>/'
        'activation-completed/$',
        ActionTemplateView.as_view(
            template_name='newsletter/subscription_%(action)s_activated.html'
        ),
        name='newsletter_action_activated'),

    # Archive views
    surl(
        '^<newsletter_slug:s>/archive/<year:Y>/<month:m>/<day:d>/<slug:s>/$',
        SubmissionArchiveDetailView.as_view(), name='newsletter_archive_detail'
    ),
    surl(
        '^<newsletter_slug:s>/archive/$',
        SubmissionArchiveIndexView.as_view(), name='newsletter_archive'
    ),
]

newsletter/models.py
import logging

from django.conf import settings
from django.contrib.sites.models import Site
from django.contrib.sites.managers import CurrentSiteManager
from django.core.mail import EmailMultiAlternatives
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import permalink
from django.template import Context
from django.template.loader import select_template
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import ugettext
from django.utils.timezone import now

from sorl.thumbnail import ImageField

from .utils import (
    make_activation_code, get_default_sites, ACTIONS
)

logger = logging.getLogger(__name__)

AUTH_USER_MODEL = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')


@python_2_unicode_compatible
class Newsletter(models.Model):
    site = models.ManyToManyField(Site, default=get_default_sites)

    title = models.CharField(
        max_length=200, verbose_name=_('newsletter title')
    )
    slug = models.SlugField(db_index=True, unique=True)

    email = models.EmailField(
        verbose_name=_('e-mail'), help_text=_('Sender e-mail')
    )
    sender = models.CharField(
        max_length=200, verbose_name=_('sender'), help_text=_('Sender name')
    )

    visible = models.BooleanField(
        default=True, verbose_name=_('visible'), db_index=True
    )

    send_html = models.BooleanField(
        default=True, verbose_name=_('send html'),
        help_text=_('Whether or not to send HTML versions of e-mails.')
    )

    objects = models.Manager()

    # Automatically filter the current site
    on_site = CurrentSiteManager()

    def get_templates(self, action):
        """
        Return a subject, text, HTML tuple with e-mail templates for
        a particular action. Returns a tuple with subject, text and e-mail
        template.
        """

        assert action in ACTIONS + ('message', ), 'Unknown action: %s' % action

        # Common substitutions for filenames
        tpl_subst = {
            'action': action,
            'newsletter': self.slug
        }

        # Common root path for all the templates
        tpl_root = 'newsletter/message/'

        subject_template = select_template([
            tpl_root + '%(newsletter)s/%(action)s_subject.txt' % tpl_subst,
            tpl_root + '%(action)s_subject.txt' % tpl_subst,
        ])

        text_template = select_template([
            tpl_root + '%(newsletter)s/%(action)s.txt' % tpl_subst,
            tpl_root + '%(action)s.txt' % tpl_subst,
        ])

        if self.send_html:
            html_template = select_template([
                tpl_root + '%(newsletter)s/%(action)s.html' % tpl_subst,
                tpl_root + '%(action)s.html' % tpl_subst,
            ])
        else:
            # HTML templates are not required
            html_template = None

        return (subject_template, text_template, html_template)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('newsletter')
        verbose_name_plural = _('newsletters')

    @permalink
    def get_absolute_url(self):
        return (
            'newsletter_detail', (),
            {'newsletter_slug': self.slug}
        )

    @permalink
    def subscribe_url(self):
        return (
            'newsletter_subscribe_request', (),
            {'newsletter_slug': self.slug}
        )

    @permalink
    def unsubscribe_url(self):
        return (
            'newsletter_unsubscribe_request', (),
            {'newsletter_slug': self.slug}
        )

    @permalink
    def update_url(self):
        return (
            'newsletter_update_request', (),
            {'newsletter_slug': self.slug}
        )

    @permalink
    def archive_url(self):
        return (
            'newsletter_archive', (),
            {'newsletter_slug': self.slug}
        )

    def get_sender(self):
        return u'%s <%s>' % (self.sender, self.email)

    def get_subscriptions(self):
        logger.debug(u'Looking up subscribers for %s', self)

        return Subscription.objects.filter(newsletter=self, subscribed=True)

    @classmethod
    def get_default(cls):
        try:
            return cls.objects.all()[0]
        except IndexError:
            return None


@python_2_unicode_compatible
class Subscription(models.Model):
    user = models.ForeignKey(
        AUTH_USER_MODEL, blank=True, null=True, verbose_name=_('user')
    )

    name_field = models.CharField(
        db_column='name', max_length=30, blank=True, null=True,
        verbose_name=_('name'), help_text=_('optional')
    )

    def get_name(self):
        if self.user:
            return self.user.get_full_name()
        return self.name_field

    def set_name(self, name):
        if not self.user:
            self.name_field = name
    name = property(get_name, set_name)

    email_field = models.EmailField(
        db_column='email', verbose_name=_('e-mail'), db_index=True,
        blank=True, null=True
    )

    def get_email(self):
        if self.user:
            return self.user.email
        return self.email_field

    def set_email(self, email):
        if not self.user:
            self.email_field = email
    email = property(get_email, set_email)

    def update(self, action):
        """
        Update subscription according to requested action:
        subscribe/unsubscribe/update/, then save the changes.
        """

        assert action in ('subscribe', 'update', 'unsubscribe')

        # If a new subscription or update, make sure it is subscribed
        # Else, unsubscribe
        if action == 'subscribe' or action == 'update':
            self.subscribed = True
        else:
            self.unsubscribed = True

        logger.debug(
            _(u'Updated subscription %(subscription)s to %(action)s.'),
            {
                'subscription': self,
                'action': action
            }
        )

        # This triggers the subscribe() and/or unsubscribe() methods, taking
        # care of stuff like maintaining the (un)subscribe date.
        self.save()

    def _subscribe(self):
        """
        Internal helper method for managing subscription state
        during subscription.
        """
        logger.debug(u'Subscribing subscription %s.', self)

        self.subscribe_date = now()
        self.subscribed = True
        self.unsubscribed = False

    def _unsubscribe(self):
        """
        Internal helper method for managing subscription state
        during unsubscription.
        """
        logger.debug(u'Unsubscribing subscription %s.', self)

        self.subscribed = False
        self.unsubscribed = True
        self.unsubscribe_date = now()

    def save(self, *args, **kwargs):
        """
        Perform some basic validation and state maintenance of Subscription.

        TODO: Move this code to a more suitable place (i.e. `clean()`) and
        cleanup the code. Refer to comment below and
        https://docs.djangoproject.com/en/dev/ref/models/instances/#django.db.models.Model.clean
        """
        assert self.user or self.email_field, \
            _('Neither an email nor a username is set. This asks for '
              'inconsistency!')
        assert ((self.user and not self.email_field) or
                (self.email_field and not self.user)), \
            _('If user is set, email must be null and vice versa.')

        # This is a lame way to find out if we have changed but using Django
        # API internals is bad practice. This is necessary to discriminate
        # from a state where we have never been subscribed but is mostly for
        # backward compatibility. It might be very useful to make this just
        # one attribute 'subscribe' later. In this case unsubscribed can be
        # replaced by a method property.

        if self.pk:
            assert(Subscription.objects.filter(pk=self.pk).count() == 1)

            subscription = Subscription.objects.get(pk=self.pk)
            old_subscribed = subscription.subscribed
            old_unsubscribed = subscription.unsubscribed

            # If we are subscribed now and we used not to be so, subscribe.
            # If we user to be unsubscribed but are not so anymore, subscribe.
            if ((self.subscribed and not old_subscribed) or
               (old_unsubscribed and not self.unsubscribed)):
                self._subscribe()

                assert not self.unsubscribed
                assert self.subscribed

            # If we are unsubcribed now and we used not to be so, unsubscribe.
            # If we used to be subscribed but are not subscribed anymore,
            # unsubscribe.
            elif ((self.unsubscribed and not old_unsubscribed) or
                  (old_subscribed and not self.subscribed)):
                self._unsubscribe()

                assert not self.subscribed
                assert self.unsubscribed
        else:
            if self.subscribed:
                self._subscribe()
            elif self.unsubscribed:
                self._unsubscribe()

        super(Subscription, self).save(*args, **kwargs)

    ip = models.GenericIPAddressField(_("IP address"), blank=True, null=True)

    newsletter = models.ForeignKey('Newsletter', verbose_name=_('newsletter'))

    create_date = models.DateTimeField(editable=False, default=now)

    activation_code = models.CharField(
        verbose_name=_('activation code'), max_length=40,
        default=make_activation_code
    )

    subscribed = models.BooleanField(
        default=False, verbose_name=_('subscribed'), db_index=True
    )
    subscribe_date = models.DateTimeField(
        verbose_name=_("subscribe date"), null=True, blank=True
    )

    # This should be a pseudo-field, I reckon.
    unsubscribed = models.BooleanField(
        default=False, verbose_name=_('unsubscribed'), db_index=True
    )

templates/base.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<!--<title>Städbolaget Märsta </title>
-->
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-123635933-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-123635933-1');
</script>

        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <title>
    {% block title %}{% endblock %}
  </title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta property="og:image" content="{% static "images/demo/backgrounds/01.png"%}">


        {# Global stylesheets #}
          <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
          <link rel="stylesheet" type="text/css" href="{% static 'css/layout.css' %}">



        {% block extra_css %}
            {# Override this in templates to add extra stylesheets #}
        {% endblock %}
    </head>

    <div class="wrapper row0">
      <div id="topbar" class="hoc clear">
        <!-- ################################################################################################ -->
        <div class="fl_left">
          <ul class="nospace">
            <li><a href="/"><i class="fa fa-lg fa-home" style="font-size: 28px;"></i></a></li>
            <li class=""><a href="{% url 'pages' slug='OM-OSS'  %}">OM OSS</a></li>
        <li class=""><a href="{% url 'pages' slug='KONTAKTA-OSS'  %}">KONTAKTA OSS</a></li>
        
            <!-- <li><a href="#">Login</a></li>
            <li><a href="#">Register</a></li> -->
          </ul>
        </div>
        <div class="fl_right">
          <ul class="nospace">
            <li><i class="fa fa-phone"></i>073 5460388 / 073 7183030</li>
            <li style='text-transform: lowercase'><i class="fa fa-envelope-o"></i> info@stadbolagetmarsta.se</li>
          </ul>
        </div>
        <!-- ################################################################################################ -->
      </div>
    </div>
    {% include "menu.html" %}

    <body class="{% block body_class %}{% endblock %}">


        {% block content %}{% endblock %}


        {% block extra_js %}
            {# Override this in templates to add extra javascript #}
        {% endblock %}
         <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/jquery.backtotop.js' %}"></script>
        <script src="{% static 'js/jquery.mobilemenu.js' %}"></script>
    </body>
    <!-- Footer Background Image Wrapper -->
<div class="bgded overlay" style=" background-color: #2a373b;">
  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
  <div class="wrapper row5">
    <div id="copyright" class="hoc clear">
      <!-- ################################################################################################ -->
      <p class="fl_left">Copyright &copy; 2020 - All Rights Reserved - <a href="#">Städbolaget Märsta HB </a></p>
      <!-- ################################################################################################ -->
    </div>
  </div>
  <!-- ################################################################################################ -->
</div>
<!-- End Footer Background Image Wrapper -->
</html>

templates/cleaning.html
{% extends "base.html" %}
{% load static %}

{% block body_class %}template-homepage{% endblock %}

{% block content %}
<div class="wrapper bgded overlay" style="background-image:url('{% static "images/demo/backgrounds/02.jpg"%}');">
    <div id="breadcrumb" class="hoc clear">
      <!-- ################################################################################################ -->
      <ul>
        <li><a href="/">Hem</a></li>
        <li><a href="#">Storstädning</a></li>
      </ul>
      <!-- ################################################################################################ -->
    </div>
  </div>
<div class="wrapper row3">
        <main class="hoc container clear">
        <section id="innerblock">

                <div class="sectiontitle">
                        <h6   class="heading"> VI HJÄLPER VÅRA KUNDER MED ALLA TYPER AV STÄDNING, ALLT FRÅN FLYTTSTÄDNING OCH KONTORSSTÄDNING TILL FÖNSTERPUTS OCH HEMSTÄDNING.</h6>
                    </div>
                    <ul class="nospace btmspace-80 group">
                            <li class="one_third first">
                              <article><i class="fa fa-external-link"></i>
                                <h2 class="heading "><a href="{% url 'pages' title='storstädning'  %}">Storstädning</a></h62
                              </article>
                            </li>
                            <li class="one_third">
                              <article><i class="fa fa-external-link"></i>
                                <h6 class="heading "><a href="{% url 'pages' title='fönsterputsning'  %}">Fönsterputsning</a></h6>
                              </article>
                            </li>
                            <li class="one_third">
                              <article><i class="fa fa-external-link"></i>
                                <h6 class="heading"><a href="{% url 'pages' title='kontorsstädning'  %}">Kontorsstädning</a></h6>
                              </article>
                            </li>
                          </ul>


                <ul class="nospace btmspace-80 group">
                  <li class="one_third first">

                    <article>
                            <i class="fa fa-external-link"></i>
                      <h6 class="heading "><a href="{% url 'pages' title='golvvård'  %}">Golvvård</a></h6>
                    </article>
                  </li>
                  <li class="one_third">
                    <article><i class="fa fa-external-link"></i>
                      <h6 class="heading"><a href="{% url 'pages' title='GOLVSLIPNING'  %}">GOLVSLIPNING</a></h6>
                    </article>
                  </li>
                  <li class="one_third">
                    <article><i class="fa fa-external-link"></i>
                      <h6 class="heading "><a href="{% url 'pages' title='butikstädning'  %}">Butikstädning</a></h6>
                    </article>
                  </li>

                </ul>
                <ul class="nospace btmspace-80 group">
                  <li class="one_third first">

                    <article>
                            <i class="fa fa-external-link"></i>
                      <h6 class="heading "><a href="{% url 'pages' title='hemstädning'  %}">Hemstädning</a></h6>
                    </article>
                  </li>
                  <li class="one_third">
                    <article><i class="fa fa-external-link"></i>
                      <h6 class="heading"><a href="{% url 'pages' title='Hotell städning'  %}">Hotell städning</a></h6>
                    </article>
                  </li>
                  <li class="one_third">
                    <article><i class="fa fa-external-link"></i>
                      <h6 class="heading "><a href="{% url 'pages' title='trappstädning'  %}">Trappstädning</a></h6>
                    </article>
                  </li>

                </ul>
                <ul class="nospace btmspace-80 group">

                  <li class="one_third first">
                    <article><i class="fa fa-external-link"></i>
                      <h6 class="heading "><a href="{% url 'pages' title='byggstädning'  %}">Byggstädning</a></h6>
                    </article>
                  </li>
                   <li class="one_third">
                    <article><i class="fa fa-external-link"></i>
                      <h6 class="heading"><a href="{% url 'pages' title='flyttstädning'  %}">Flyttstädning</a></h6>
                    </article>
                  </li>
                  <li class="one_third">
                    <article><i class="fa fa-external-link"></i>
                      <h6 class="heading "><a href="{% url 'pages' title='skolor och dagis'  %}">Skolor och dagis</a></h6>
                    </article>
                  </li>
                </ul>
                <!-- <p class="center"><a class="btn" href="#">Eleifend dui auctor</a></p> -->
              </section>
              </main>
  {% include "contact_us.html" %}

</div>
{% endblock %}

templates/contact_us.html
{% load static %}

<div class="wrapper row2 ">


<section class="hoc container clear testimonials">
 <div class="sectiontitle">
            <h6   class="heading"> Bli kontaktad av oss.</h6>

        </div>
    <form method="post" >
            {% csrf_token %}
                    <div class="row">
                            {% for field in form  %}
                            <small id="" class="text-danger">
                                    {{ field.errors }}
                            </small>
                            {% if forloop.last %} <div class="col-sm-12">
                           {% else %}
                           <div class="col-sm-6">
                           {% endif %}
                           {{ item }}
                           <div class="">
                                {{ field.label_tag }}
                           </div> {{ field }}
                           </div>
                            {% endfor %}
                    </div>
                    <br>
                    <button type="submit" class="btn btn-danger pull-right" >Skicka förfrågan</button>
      </form>
      </section>
  </div>

templates/detailpage.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{% for Descripton in pagedetail %} {{Descripton.Title |safe }} - Städbolaget Märsta

{% endfor %}
{% endblock %}
{% block body_class %}template-homepage{% endblock %}

{% block content %}
<div class="wrapper row3">
    <main class="hoc container clear">
      <!-- main body -->
      <!-- ################################################################################################ -->
      {% for i in pagedetail %}
      {%if i.hassidemenu == True %}
      {% include "side-menu.html" %}
      {%else%}
      {%endif%}
      {% endfor %}
      <div class="content three_quarter">
        <!-- ################################################################################################ -->
        {% for Descripton in pagedetail %}
            <!-- {{Descripton.name}}
            {{Descripton.menu}} -->

            {{Descripton.Descripton |safe }}
        {% endfor %}
        </div>
      <!-- ################################################################################################ -->
      <!-- / main body -->
      <div class="clear"></div>
    </main>
    
    
  </div>
  

  {% include "contact_us.html" %}

  {% endblock %}

templates/menu.html
{% load static %}

<div class="wrapper row1">
    <header id="header" class="hoc clear">
      <!-- ################################################################################################ -->
      <div id="logo" class="fl_left">
        <h1><a href="/">Städbolaget Märsta </a></h1>
      </a>
      </div>
      <nav id="mainav" class="fl_right rounded-circle">
        <ul class="clear">
          {%for n ,m in Category.items %}
            <li class="  {% if n.url in request.path %}active{% endif %}" ><a  class="{% if m %}drop{%endif%} "href="{% url 'pages' slug=n.url  %}">{{n.menu}}</a>
              {% if not m %}</li>{%endif%}
              <ul>
              {%for i in m %}
  
              {% if i.name%}
            
              <li class="  {% if i.url in request.path %}active{% endif %}" ><a  href="{% url 'pages' slug=i.url %}">{{i.name}}</a></li>
                      
              {%else%}
  
              {%endif%}
           
            {% endfor %}
            </li>
          </ul> 
          {%endfor%}
        </li>
        </ul>
         </nav>
        
    </header>
  </div>
 

templates/propertyservice.html
{% extends "base.html" %}
{% load static %}

{% block body_class %}template-homepage{% endblock %}

{% block content %}
<div class="wrapper bgded overlay" style="background-image:url('{% static "images/demo/backgrounds/03.jpg"%}');">
    <div id="breadcrumb" class="hoc clear"> 
      <!-- ################################################################################################ -->
      <ul>
        <li><a href="#">Hem</a></li>
        <li><a href="#">Tjänster</a></li>
        <li><a href="#">Fastighetsservice</a></li>
      </ul>
      <!-- ################################################################################################ -->
    </div>
  </div>
<div class="wrapper row3">
        <main class="hoc container clear"> 
        <section id="innerblock">
                
                <div class="sectiontitle">
                        <h6   class="heading"> Vi har bred kompetens inom fastighetsservice. Hos oss får ni alltid bra service till rätt pris, och vi erbjuder en mängd olika tjänster inom fastighetsservice – allt från jourtjänster till snöröjning på tak.</h6>
                    </div>
                    <ul class="nospace btmspace-80 group">
                            <li class="one_third first">
                              <article><i class="fa fa-external-link"></i>
                                <h2 class="heading "><a href="#">trappstädning</a></h6>
                              </article>
                            </li>
                            <li class="one_third">
                              <article><i class="fa fa-external-link"></i>
                                <h6 class="heading "><a href="#">byggstädning</a></h6>
                              </article>
                            </li>
                            <li class="one_third">
                              <article><i class="fa fa-external-link"></i>
                                <h6 class="heading"><a href="#">flyttstädning</a></h6>
                              </article>
                            </li>
                          </ul>
                <!-- <p class="center"><a class="btn" href="#">Eleifend dui auctor</a></p> -->
              </section>
              </main>       
  {% include "contact_us.html" %}

</div>
{% endblock %}

templates/review.html
{% load static %}

<div class="">
<iframe src="https://widget.reco.se/v2/widget/4027221?mode=HORIZONTAL_QUOTE" width="95%" height="225" scrolling="no" style="border:none;display:block" data-reactroot=""></iframe>
</div>

templates/side-menu.html
<div class="sidebar one_quarter first">
    <!-- ################################################################################################ -->
    <h6>Navigator</h6>
   
    <nav class="sdb_holder">
      <ul>
        {%for n ,m in Category.items %}
          <li ><a  class=""href="{% url 'pages' slug=n.url  %}">{{n.menu}}</a>
          
            {%for i in m %}
            {% if i.name%}
          <ul>
            <li class="  " ><a href="{% url 'pages' slug=i.url %}">{{i.name}}</a></li>

          </ul>
          
         
            {%else%}

            {%endif%}
          {% endfor %}
        </li>
        {%endfor%}
      </ul>
       </nav>

    <!-- ################################################################################################ -->
  </div>

templates/subscribe.html
{% load static %}

<div class="wrapper bgded overlay" style="background-image:url('images/demo/backgrounds/02.png');">
    <article class="hoc cta clear"> 
      <!-- ################################################################################################ -->
      <h6 class=" center first">LÄMNA ER E-POSTADRESS OCH ERHÅLL VÅRA KAMPANJER OCH NYHETSBREV</h6>
      
        <div class="row" style="    width: 70%;
        margin: 0 auto;" >
            <form  id= "subID"enctype="multipart/form-data" method="post" action="/newsletter/news/subscribe/">
        {% csrf_token %} 
            <div class="" id="emailbox" style=" text-align: center;">
                <div class="col-sm-9 ">
                    <input placeholder="E-postadress"type="email" name="email_field" required="" id="id_email_field"class="form-control " >
                </div>
                <div class="col-sm-2">
                        <button class="btn btn-white" id="id_submit" name="submit" value="Subscribe" type="submit">Subscribe</button>
                </div>
            </div>
            <div id="subsuccess" hidden style=" text-align: center;">
                <p> prenumererade framgångsrikt!!</p>
            </div>
            <div id="subfailed" hidden style=" text-align: center;">
                <p> Något gick fel!</p>
            </div>
        </div>
            
        
    </form>        <!-- ################################################################################################ -->
    </article>
  </div>

  <script type="text/javascript">
    var frm = $('#subID');
    frm.submit(function () {
        $.ajax({
            type: frm.attr('post'),
            url: frm.attr('action'),
            data: frm.serialize(),
            success: function (data) {
                $("#SOME-DIV").html(data);
                $("#emailbox").hide(); 
                $("#subsuccess").show(); 
            },
            error: function(data) {
                $("#subfailed").html("Något gick fel!");
            }
        });
        return false;
    });
</script>